apiVersion: apps/v1
kind: Deployment
metadata:
  name: assign-deployment
  labels:
    app: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: devdeep142/dcrimg1:latest
        ports:
        - containerPort: 8080
