apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.Namespacename }}
  name: {{ .Values.Servicename }}
spec:
  
  ports:
  - port: 8080
    targetPort: 31000
    protocol: TCP
  type: LoadBalancer  
  selector:
    {{- toYaml .Values.selector| nindent 4 }}
