Namespacename: default

Deploymentname: deployment

Servicename: service



labels:
  app.kubernetes.io/name: webserver
 
matchLabels:
  app.kubernetes.io/name: webserver
  
selector:
  app.kubernetes.io/name: webserver

containers:
  name: webserver
  image: <dockerid>/docker-server:v1
  imagePullPolicy: Always
  
